-- SAMPLE content so the site isn't empty on day one.
-- Photos are from Unsplash. Replace projects, services and testimonials with real ones from the admin dashboard.

INSERT INTO services (slug,title,summary,description,image,sort_order) VALUES ('interior-design','Interior Design','Full-service design from concept to completion.','We plan your space from the ground up: layout, colour palette, materials, furniture, lighting and décor, then manage the work until it is ready to live in.','https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1600&q=80',0);
INSERT INTO services (slug,title,summary,description,image,sort_order) VALUES ('interior-decoration','Interior Decoration','Styling, furnishing and finishing touches.','Already happy with the structure? We transform rooms with furniture, curtains, rugs, art, accessories and lighting that reflect your taste.','https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=80',1);
INSERT INTO services (slug,title,summary,description,image,sort_order) VALUES ('kitchen-design','Kitchen Design & Remodelling','Kitchens that work as good as they look.','Custom kitchen layouts, cabinetry, worktops, islands, storage and lighting, designed around how you cook and entertain.','https://images.unsplash.com/photo-1671197244266-73129c97c096?auto=format&fit=crop&w=1600&q=80',2);
INSERT INTO services (slug,title,summary,description,image,sort_order) VALUES ('bedroom-styling','Bedroom & Wardrobe Design','Restful bedrooms and smart storage.','Upholstered headboards, built-in wardrobes, bedding and soft furnishings to give you a calm, hotel-like retreat.','https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',3);
INSERT INTO services (slug,title,summary,description,image,sort_order) VALUES ('office-commercial','Office & Commercial Fit-out','Workspaces, shops, salons and restaurants.','Commercial interiors that reflect your brand, impress your customers and help your team work better.','https://images.unsplash.com/photo-1604328698692-f76ea9498e76?auto=format&fit=crop&w=1600&q=80',4);
INSERT INTO services (slug,title,summary,description,image,sort_order) VALUES ('short-let-staging','Short-let & Home Staging','Spaces that rent and sell faster.','We furnish and style short-let apartments and homes for sale so they photograph beautifully and attract more bookings and buyers.','https://images.unsplash.com/photo-1611596188718-840151555242?auto=format&fit=crop&w=1600&q=80',5);

INSERT INTO projects (slug,title,category,location,year,duration,scope,summary,description,cover_image,featured,sort_order) VALUES ('warm-contemporary-living-room','Warm Contemporary Living Room','Residential','Abuja','2026','6 weeks','Living room redesign, custom sofa, lighting, art curation','A bright family living room reworked around soft neutrals, natural wood and layered lighting.','The brief was a living room that feels calm in the day and cosy at night. We opened up the layout, introduced a custom low-profile sofa, warm oak accents and a layered lighting plan with dimmable pendants and wall washers. Curtains, rugs and art were sourced to pull the palette together, leaving a space that works for everyday family life and for hosting guests.','https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1600&q=80',1,0);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='warm-contemporary-living-room'),'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1600&q=80','',0);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='warm-contemporary-living-room'),'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=1600&q=80','',1);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='warm-contemporary-living-room'),'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=80','',2);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='warm-contemporary-living-room'),'https://images.unsplash.com/photo-1600494448850-6013c64ba722?auto=format&fit=crop&w=1600&q=80','',3);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='warm-contemporary-living-room'),'https://images.unsplash.com/photo-1633505899118-4ca6bd143043?auto=format&fit=crop&w=1600&q=80','',4);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='warm-contemporary-living-room'),'https://images.unsplash.com/photo-1618221381711-42ca8ab6e908?auto=format&fit=crop&w=1600&q=80','',5);

INSERT INTO projects (slug,title,category,location,year,duration,scope,summary,description,cover_image,featured,sort_order) VALUES ('serene-master-suite','Serene Master Suite','Residential','Lagos','2026','5 weeks','Bedroom styling, upholstered headboard, wardrobes, soft furnishings','A hotel-inspired master bedroom with an upholstered headboard, statement chandelier and soft layered bedding.','We designed this suite to feel like a boutique hotel at home. A full-height upholstered headboard anchors the room, framed by bedside pendants and a statement chandelier. Built-in wardrobes keep the space clutter-free, while blackout drapery, premium bedding and a cream and gold palette complete the calm, restful mood.','https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',1,1);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='serene-master-suite'),'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80','',0);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='serene-master-suite'),'https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?auto=format&fit=crop&w=1600&q=80','',1);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='serene-master-suite'),'https://images.unsplash.com/photo-1600210491305-7396500b5b31?auto=format&fit=crop&w=1600&q=80','',2);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='serene-master-suite'),'https://images.unsplash.com/photo-1631048501851-4aa85ffc3be8?auto=format&fit=crop&w=1600&q=80','',3);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='serene-master-suite'),'https://images.unsplash.com/photo-1625334782252-da92af3ad887?auto=format&fit=crop&w=1600&q=80','',4);

INSERT INTO projects (slug,title,category,location,year,duration,scope,summary,description,cover_image,featured,sort_order) VALUES ('the-chefs-kitchen','The Chef''s Kitchen','Residential','Abuja','2025','8 weeks','Kitchen remodel, island, cabinetry, worktops, lighting','A modern kitchen built around a generous island, marble-look worktops and smart storage.','This kitchen was designed for a family that cooks and entertains often. We planned a large central island with seating for four, handle-less cabinetry with concealed storage, marble-look worktops and integrated appliances. Pendant lighting over the island and under-cabinet strips make it both practical and beautiful.','https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1600&q=80',1,2);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='the-chefs-kitchen'),'https://images.unsplash.com/photo-1502005097973-6a7082348e28?auto=format&fit=crop&w=1600&q=80','',0);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='the-chefs-kitchen'),'https://images.unsplash.com/photo-1671197244266-73129c97c096?auto=format&fit=crop&w=1600&q=80','',1);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='the-chefs-kitchen'),'https://images.unsplash.com/photo-1512916194211-3f2b7f5f7de3?auto=format&fit=crop&w=1600&q=80','',2);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='the-chefs-kitchen'),'https://images.unsplash.com/photo-1592506119503-c0b18879bd5a?auto=format&fit=crop&w=1600&q=80','',3);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='the-chefs-kitchen'),'https://images.unsplash.com/photo-1643949915134-73a4c880f7c7?auto=format&fit=crop&w=1600&q=80','',4);

INSERT INTO projects (slug,title,category,location,year,duration,scope,summary,description,cover_image,featured,sort_order) VALUES ('modern-workspace','Modern Corporate Workspace','Commercial','Abuja','2025','10 weeks','Office fit-out, meeting rooms, lounge, branding','An office fit-out with open workstations, a breakout lounge and meeting rooms that reflect the brand.','The client needed an office that helps teams focus and collaborate. We zoned the floor into open workstations, quiet booths, two meeting rooms and a relaxed breakout lounge with greenery. Acoustic panels, ergonomic furniture and subtle brand colours give the space a professional yet welcoming feel.','https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1600&q=80',1,3);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='modern-workspace'),'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1600&q=80','',0);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='modern-workspace'),'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?auto=format&fit=crop&w=1600&q=80','',1);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='modern-workspace'),'https://images.unsplash.com/photo-1579487785973-74d2ca7abdd5?auto=format&fit=crop&w=1600&q=80','',2);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='modern-workspace'),'https://images.unsplash.com/photo-1606836576983-8b458e75221d?auto=format&fit=crop&w=1600&q=80','',3);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='modern-workspace'),'https://images.unsplash.com/photo-1549637642-90187f64f420?auto=format&fit=crop&w=1600&q=80','',4);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='modern-workspace'),'https://images.unsplash.com/photo-1560264280-88b68371db39?auto=format&fit=crop&w=1600&q=80','',5);

INSERT INTO projects (slug,title,category,location,year,duration,scope,summary,description,cover_image,featured,sort_order) VALUES ('family-dining-room','Elegant Family Dining Room','Residential','Port Harcourt','2025','4 weeks','Dining furniture, lighting, wall finishes, styling','A dining room made for long family dinners, with a solid wood table, sculptural lighting and warm wall finishes.','We centred this room on a solid wood dining table for eight, paired with upholstered chairs and a sculptural pendant. A textured wall finish, a sideboard for storage and carefully chosen art and accessories make it a room the family actually wants to gather in.','https://images.unsplash.com/photo-1611596188718-840151555242?auto=format&fit=crop&w=1600&q=80',0,4);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='family-dining-room'),'https://images.unsplash.com/photo-1611596188718-840151555242?auto=format&fit=crop&w=1600&q=80','',0);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='family-dining-room'),'https://images.unsplash.com/photo-1614597445336-8a67e9314d91?auto=format&fit=crop&w=1600&q=80','',1);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='family-dining-room'),'https://images.unsplash.com/photo-1600488999806-8efb986d87b1?auto=format&fit=crop&w=1600&q=80','',2);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='family-dining-room'),'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=1600&q=80','',3);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='family-dining-room'),'https://images.unsplash.com/photo-1634389312178-50613e56acda?auto=format&fit=crop&w=1600&q=80','',4);

INSERT INTO projects (slug,title,category,location,year,duration,scope,summary,description,cover_image,featured,sort_order) VALUES ('neutral-luxury-apartment','Neutral Luxury Apartment','Residential','Lagos','2026','12 weeks','Full apartment interior: living, bedrooms, dining','A complete apartment interior in soft neutrals, from the living area to the bedrooms.','This full-apartment project covered every room. We kept a consistent neutral palette with texture coming from boucle, linen, timber and stone, so each space flows into the next. Furniture, lighting, window treatments and décor were all specified and installed by our team, ready for the owners to move straight in.','https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1600&q=80',0,5);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='neutral-luxury-apartment'),'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1600&q=80','',0);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='neutral-luxury-apartment'),'https://images.unsplash.com/photo-1564078516393-cf04bd966897?auto=format&fit=crop&w=1600&q=80','',1);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='neutral-luxury-apartment'),'https://images.unsplash.com/photo-1606744888344-493238951221?auto=format&fit=crop&w=1600&q=80','',2);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='neutral-luxury-apartment'),'https://images.unsplash.com/photo-1633330977020-2bdfb8530cc2?auto=format&fit=crop&w=1600&q=80','',3);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='neutral-luxury-apartment'),'https://images.unsplash.com/photo-1696762932825-2737db830bbe?auto=format&fit=crop&w=1600&q=80','',4);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='neutral-luxury-apartment'),'https://images.unsplash.com/photo-1648634158203-199accfd7afc?auto=format&fit=crop&w=1600&q=80','',5);

INSERT INTO projects (slug,title,category,location,year,duration,scope,summary,description,cover_image,featured,sort_order) VALUES ('open-plan-kitchen-dining','Open-Plan Kitchen & Dining','Residential','Abuja','2026','7 weeks','Kitchen and dining remodel, joinery, lighting','An open-plan kitchen and dining area that brings cooking, eating and family time into one space.','Walls came down to create one bright open-plan space. A new kitchen with timber and white cabinetry flows into a dining zone defined by a statement pendant and a feature rug. Clever joinery keeps everything stored away, so the space stays open and calm.','https://images.unsplash.com/photo-1649083048597-d7b4f1e8a386?auto=format&fit=crop&w=1600&q=80',0,6);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='open-plan-kitchen-dining'),'https://images.unsplash.com/photo-1649083048597-d7b4f1e8a386?auto=format&fit=crop&w=1600&q=80','',0);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='open-plan-kitchen-dining'),'https://images.unsplash.com/photo-1649083048428-3d8ed23a3ce0?auto=format&fit=crop&w=1600&q=80','',1);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='open-plan-kitchen-dining'),'https://images.unsplash.com/photo-1663811396777-05505d999151?auto=format&fit=crop&w=1600&q=80','',2);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='open-plan-kitchen-dining'),'https://images.unsplash.com/photo-1610177534644-34d881503b83?auto=format&fit=crop&w=1600&q=80','',3);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='open-plan-kitchen-dining'),'https://images.unsplash.com/photo-1657524398377-567034729507?auto=format&fit=crop&w=1600&q=80','',4);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='open-plan-kitchen-dining'),'https://images.unsplash.com/photo-1622653533660-a1538fe8424c?auto=format&fit=crop&w=1600&q=80','',5);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='open-plan-kitchen-dining'),'https://images.unsplash.com/photo-1593136596203-7212b076f4d2?auto=format&fit=crop&w=1600&q=80','',6);

INSERT INTO projects (slug,title,category,location,year,duration,scope,summary,description,cover_image,featured,sort_order) VALUES ('boutique-guest-rooms','Boutique Guest Rooms','Hospitality','Enugu','2025','9 weeks','Short-let and guest house rooms, furniture, soft furnishings','Guest rooms for a short-let property, designed to photograph beautifully and wear well.','For this short-let property we designed a set of guest rooms that feel premium but are durable and easy to maintain. Each room has a consistent look with its own accent colour, quality bedding, task lighting and a compact work corner, helping the owner earn great reviews.','https://images.unsplash.com/photo-1663811397207-418a92396ad5?auto=format&fit=crop&w=1600&q=80',0,7);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='boutique-guest-rooms'),'https://images.unsplash.com/photo-1663811397207-418a92396ad5?auto=format&fit=crop&w=1600&q=80','',0);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='boutique-guest-rooms'),'https://images.unsplash.com/photo-1633948393301-d43e3ec0e5cd?auto=format&fit=crop&w=1600&q=80','',1);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='boutique-guest-rooms'),'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1600&q=80','',2);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='boutique-guest-rooms'),'https://images.unsplash.com/photo-1656122381069-9ec666d95cf1?auto=format&fit=crop&w=1600&q=80','',3);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='boutique-guest-rooms'),'https://images.unsplash.com/photo-1635321350281-e2a91ecffd00?auto=format&fit=crop&w=1600&q=80','',4);
INSERT INTO project_photos (project_id,url,caption,sort_order) VALUES ((SELECT id FROM projects WHERE slug='boutique-guest-rooms'),'https://images.unsplash.com/photo-1585128903994-9788298932a6?auto=format&fit=crop&w=1600&q=80','',5);
