-- Content from the Jopearl Homemakers International company profile.
-- Replaces the services and updates the website text. Logo, colours, sizes and photos are NOT changed.

-- Services
DELETE FROM services;
INSERT INTO services (slug, title, summary, description, image, sort_order, active) VALUES ('project-design-and-rendering', 'Project Design and Rendering', 'See your space in full detail before a single wall is touched.', 'Every great project starts with a clear design. We develop concepts, layouts, material and colour schemes, then produce realistic 3D renders, so you can see exactly how your home or commercial space will look and feel before work begins.

Our designs are created around your specifications and preferences, and refined with you until you''re completely happy.', 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1600&q=80', 0, 1);
INSERT INTO services (slug, title, summary, description, image, sort_order, active) VALUES ('space-planning', 'Space Planning', 'Layouts that make every square metre work beautifully.', 'Good design begins with how a space flows. We study how you live or work, then plan the layout of rooms, furniture, storage, lighting and circulation, so every area is comfortable, practical and beautiful.

Whether it''s a single room, a full apartment or a commercial floor, space planning ensures nothing is wasted and everything has its place.', 'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1600&q=80', 1, 1);
INSERT INTO services (slug, title, summary, description, image, sort_order, active) VALUES ('hardware-interior-exterior-finishing', 'Hardware Interior & Exterior Finishing', 'The fixed finishes that give a building its quality, from carcass to completion.', 'We take projects from carcass to completion, handling the permanent finishes that define a space inside and out. This includes ceilings, flooring, wall finishes and cladding, built-in joinery, kitchens and wardrobes, doors, and exterior and facade finishing.

We use only genuine materials and skilled workmanship, so the finish looks exceptional and stands the test of time.', 'https://images.unsplash.com/photo-1671197244266-73129c97c096?auto=format&fit=crop&w=1600&q=80', 2, 1);
INSERT INTO services (slug, title, summary, description, image, sort_order, active) VALUES ('software-interior-finishing-and-furnishing', 'Software Interior Finishing and Furnishing', 'Furniture, fabrics, lighting and décor that bring the space to life.', 'Once the structure is complete, we furnish and style it. We source and install furniture, curtains and blinds, rugs, decorative lighting, wall art, accessories and soft furnishings, all chosen to complete the design and reflect your taste.

The result is a finished, move-in-ready space that truly lets you experience the difference.', 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80', 3, 1);
INSERT INTO services (slug, title, summary, description, image, sort_order, active) VALUES ('facility-management-services', 'Facility Management Services', 'Keeping your property in excellent condition long after handover.', 'A beautiful space deserves to stay beautiful. Our facility management services help residential and commercial property owners keep their buildings well maintained, functional and presentable, with planned upkeep and prompt attention when something needs fixing.

Talk to us about a maintenance arrangement that suits your property.', 'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?auto=format&fit=crop&w=1600&q=80', 4, 1);

-- Website text: only applies where the section was already saved from the dashboard;
-- otherwise the new defaults in src/lib/site-defaults.ts are used automatically.
UPDATE settings SET value = json_set(value, '$.name', 'Jo-pearl Homemakers'), updated_at = datetime('now') WHERE key = 'brand';
UPDATE settings SET value = json_set(value, '$.text', 'Since 2006 · Over 3,000 projects delivered · Call or WhatsApp +234 703 130 6790'), updated_at = datetime('now') WHERE key = 'topBar';
UPDATE settings SET value = json_set(value, '$.eyebrow', 'Since 2006 · Luxury Designs', '$.title', 'Luxury designs, from carcass to finishing', '$.subtitle', 'Project design and execution for residential and commercial spaces. Over 3,000 projects delivered in 20 years, always with genuine materials and to your exact specification.', '$.primaryCta', json('{"label":"Our Services","to":"/services"}'), '$.secondaryCta', json('{"label":"Get a Quote","to":"/quote"}')), updated_at = datetime('now') WHERE key = 'hero';
UPDATE settings SET value = json_set(value, '$.introTitle', 'Extraordinary designs, delivered with genuine materials.', '$.introText', 'Jo-pearl Homemakers International was established on 10th July 2006. We design and execute residential and commercial projects from carcass to finishing and furnishing, always according to our clients'' specifications and preferences.

We create extraordinary designs for every project category, with high professionalism and, most importantly, genuine materials. We don''t compromise, and we always deliver the very best.', '$.stats', json('[{"value":"2006","label":"Established"},{"value":"3,000+","label":"Projects delivered"},{"value":"20 yrs","label":"Of excellence"}]'), '$.process', json('[{"title":"Brief & site visit","text":"We listen to your needs, visit the site and agree your specifications, style and budget."},{"title":"Design & rendering","text":"Space planning, drawings and 3D renders, so you see the finished space before work starts."},{"title":"Execution","text":"Hardware and software finishing, from carcass to furnishing, using genuine materials only."},{"title":"Handover & care","text":"A finished masterpiece, then facility management to keep it at its best."}]'), '$.ctaText', 'Tell us about your residential or commercial project and we''ll get back to you with ideas and a quotation.'), updated_at = datetime('now') WHERE key = 'home';
UPDATE settings SET value = json_set(value, '$.title', 'About Jo-pearl Homemakers International', '$.intro', 'Established on 10th July 2006. Over 3,000 projects delivered across 20 years.', '$.story', 'Jo-pearl Homemakers International was established on 10th July 2006. Over the past 20 years we have delivered more than 3,000 projects, always ensuring excellent service delivery according to our clients'' specifications and preferences.

We design and execute from carcass to finishing and furnishing, for both residential and commercial projects. Our projects are exceptional and always a masterpiece, hence our slogan: ...experience the difference.

For many years since 2006, we have created mind-blowing innovations and unique designs. We look forward to partnering with you on your project, and we''re committed to rendering exceptional service delivery.

Jo-pearl Homemakers is a member of Jopearl Int''l Ltd (RC 958458).', '$.values', json('[{"title":"Genuine materials","text":"We never cut corners on materials. Quality you can see and feel for years."},{"title":"Your specification","text":"Every project is delivered according to your specifications and preferences."},{"title":"Carcass to furnishing","text":"One team from the bare structure to the final finishing and furnishing."},{"title":"Only the very best","text":"We don''t compromise. Every project is designed and delivered as a masterpiece."}]')), updated_at = datetime('now') WHERE key = 'about';
UPDATE settings SET value = json_set(value, '$.portfolioIntro', 'A selection of the residential and commercial projects we''ve designed and delivered.', '$.servicesIntro', 'Design, planning, finishing, furnishing and facility management: one team for the whole life of your space.', '$.quoteIntro', 'Tell us about your project. The more detail you share, the more accurate our quotation will be.', '$.contactIntro', 'Call, WhatsApp, email or visit our office in Lekki. We look forward to partnering with you on your project.'), updated_at = datetime('now') WHERE key = 'pages';
UPDATE settings SET value = json_set(value, '$.phone', '+234 703 130 6790', '$.whatsapp', '+234 703 130 6790', '$.whatsappMessage', 'Hello Jo-pearl Homemakers, I''d like to make an enquiry about a project.', '$.email', 'info@jopearlhomemakers.com', '$.address', 'Friends Colony Estate, Osapa London,
Lekki, Lagos, Nigeria', '$.hours', ''), updated_at = datetime('now') WHERE key = 'contact';
UPDATE settings SET value = json_set(value, '$.instagram', 'https://www.instagram.com/jopearlhomemakersintl/'), updated_at = datetime('now') WHERE key = 'social';
UPDATE settings SET value = json_set(value, '$.about', 'Project design and execution for residential and commercial spaces, from carcass to finishing and furnishing. Established 2006 · RC 958458 · A member of Jopearl Int''l Ltd.'), updated_at = datetime('now') WHERE key = 'footer';
UPDATE settings SET value = json_set(value, '$.title', 'Jo-pearl Homemakers | Interior Design, Finishing & Furnishing in Lagos', '$.description', 'Since 2006, Jo-pearl Homemakers International has delivered over 3,000 residential and commercial projects: design and rendering, space planning, interior and exterior finishing, furnishing and facility management. Lekki, Lagos.'), updated_at = datetime('now') WHERE key = 'seo';
UPDATE settings SET value = json_set(value, '$.intro', 'Thank you for choosing Jo-pearl Homemakers International. Below is our quotation for your project.', '$.acceptMessage', 'Thank you for choosing Jo-pearl! We''ve received your acceptance and our team will contact you shortly to agree the next steps.'), updated_at = datetime('now') WHERE key = 'quotes';
UPDATE settings SET value = json_set(value, '$.title', 'Chat with Jo-pearl', '$.greeting', 'Hi there! 👋 Ask us anything about your project, our services or a quotation. We''ll reply as soon as we can.'), updated_at = datetime('now') WHERE key = 'chat';

-- FAQs: refresh two answers and add questions from the profile
UPDATE faqs SET answer = 'Yes. Since 2006 we''ve delivered residential and commercial projects: homes, apartments and estates, as well as offices, retail and hospitality spaces.' WHERE question = 'Do you work on offices and commercial spaces?';
UPDATE faqs SET answer = 'Send us a message on the chat, request a quote or book a consultation. You can also call or WhatsApp us on +234 703 130 6790. We look forward to partnering with you on your project.' WHERE question = 'How do I get started?';
INSERT INTO faqs (question, answer, sort_order) VALUES ('How long have you been in business?', 'Jopearl Homemakers International was established on 10th July 2006. Over the past 20 years we have delivered more than 3,000 projects, always according to our clients'' specifications and preferences.', 6);
INSERT INTO faqs (question, answer, sort_order) VALUES ('Do you handle the whole project, or only the design?', 'Both. We design and execute from carcass to finishing and furnishing: design and rendering, space planning, hardware interior and exterior finishing, and software finishing and furnishing. After handover, we also offer facility management.', 7);
INSERT INTO faqs (question, answer, sort_order) VALUES ('What is facility management?', 'It''s how we help you keep your property in excellent condition after the project is finished, with planned maintenance and prompt attention when something needs fixing. Contact us to discuss what your property needs.', 8);
INSERT INTO faqs (question, answer, sort_order) VALUES ('Where is your office?', 'Our office is at Friends Colony Estate, Osapa London, Lekki, Lagos. Call or WhatsApp +234 703 130 6790 to arrange a visit.', 9);

